version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ac-agency
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - './public/:/usr/src/app'
      - './docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker_config/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    ports:
      - "8081:8081"
    user: 1000:1000
    depends_on:
      - mysql

  encore:
    image: node:14.10-alpine
    volumes:
      - .:/var/www/ac-agency
    command: >
      sh -c "yarn install && yarn run encore dev --watch"
    working_dir: /var/www/ac-agency

volumes:
  mysql:
